//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyYahtzee.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MYYAHTZEE_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDI_FIVE                        129
#define IDI_FOUR                        130
#define IDC_PENCIL                      130
#define IDI_THREE                       131
#define IDI_TWO                         132
#define IDD_YAHTZEE                     132
#define IDI_ONE                         133
#define IDI_SIX                         134
#define IDD_HIGHSCORE                   134
#define IDD_HIGHSCORESHEET              135
#define IDB_BACKGROUND                  137
#define IDB_BACKGROUND1                 138
#define IDD_SETTINGS                    139
#define IDC_ROLL_DICE                   1000
#define IDC_DIE_ONE                     1001
#define IDC_DIE_TWO                     1002
#define IDC_DIE_THREE                   1003
#define IDC_DIE_FOUR                    1004
#define IDC_DIE_FIVE                    1005
#define IDC_ONE_1                       1007
#define IDC_GAMETOTAL                   1008
#define IDC_HOLD5                       1009
#define IDC_HOLD4                       1010
#define IDC_HOLD3                       1011
#define IDC_HOLD2                       1012
#define IDC_TWO_1                       1013
#define IDC_THREE_1                     1014
#define IDC_SIX_1                       1015
#define IDC_FOUR_1                      1016
#define IDC_FIVE_1                      1017
#define IDC_ONE_2                       1018
#define IDC_TWO_2                       1019
#define IDC_THREE_2                     1020
#define IDC_SIX_2                       1021
#define IDC_FOUR_2                      1022
#define IDC_FIVE_2                      1023
#define IDC_ONE_3                       1024
#define IDC_TWO_3                       1025
#define IDC_THREE_3                     1026
#define IDC_SIX_3                       1027
#define IDC_FOUR_3                      1028
#define IDC_FIVE_3                      1029
#define IDC_TOTAL_1                     1030
#define IDC_TOTAL_2                     1031
#define IDC_TOTAL_3                     1032
#define IDC_BONUS_1                     1033
#define IDC_BONUS_2                     1034
#define IDC_BONUS_3                     1035
#define IDC_SECTIONONE_1                1036
#define IDC_SECTIONONE_2                1037
#define IDC_SECTIONONE_3                1038
#define IDC_3OFKIND_1                   1039
#define IDC_4OFKIND_1                   1040
#define IDC_FULLHOUSE_1                 1041
#define IDC_YAHTZEE_1                   1042
#define IDC_SMALLSTR_1                  1043
#define IDC_LARGESTR_1                  1044
#define IDC_3OFKIND_2                   1045
#define IDC_4OFKIND_2                   1046
#define IDC_FULLHOUSE_2                 1047
#define IDC_YAHTZEE_2                   1048
#define IDC_SMALLSTR_2                  1049
#define IDC_LARGESTR_2                  1050
#define IDC_3OFKIND_3                   1051
#define IDC_4OFKIND_3                   1052
#define IDC_FULLHOUSE_3                 1053
#define IDC_YAHTZEE_3                   1054
#define IDC_SMALLSTR_3                  1055
#define IDC_LARGESTR_3                  1056
#define IDC_CHANCE_1                    1057
#define IDC_CHANCE_2                    1058
#define IDC_CHANCE_3                    1059
#define IDC_SECTIONTWO_1                1060
#define IDC_SECTIONTWO_2                1061
#define IDC_SECTIONTWO_3                1062
#define IDC_HOLD1                       1063
#define IDC_CLICKONDICE                 1064
#define IDC_DICEFRAME                   1065
#define IDC_UNDO                        1066
#define IDC_YAHTZEE                     1067
#define IDC_BUTTON1                     1068
#define IDC_EDIT1                       1072
#define IDC_SCORE                       1073
#define IDC_PLAYERNAME                  1074
#define IDC_DATE                        1075
#define IDC_PLAYER1                     1076
#define IDC_PLAYER2                     1077
#define IDC_PLAYER3                     1078
#define IDC_PLAYER4                     1079
#define IDC_PLAYER5                     1080
#define IDC_PLAYER6                     1081
#define IDC_PLAYER7                     1082
#define IDC_PLAYER8                     1083
#define IDC_PLAYER9                     1084
#define IDC_PLAYER10                    1085
#define IDC_SCORE1                      1086
#define IDC_SCORE2                      1087
#define IDC_SCORE3                      1088
#define IDC_SCORE4                      1089
#define IDC_SCORE5                      1090
#define IDC_SCORE6                      1091
#define IDC_SCORE7                      1092
#define IDC_SCORE8                      1093
#define IDC_SCORE9                      1094
#define IDC_SCORE10                     1095
#define IDC_DATE1                       1096
#define IDC_DATE2                       1097
#define IDC_DATE3                       1098
#define IDC_DATE4                       1099
#define IDC_DATE5                       1100
#define IDC_DATE6                       1101
#define IDC_DATE7                       1102
#define IDC_DATE8                       1103
#define IDC_DATE9                       1104
#define IDC_DATE10                      1105
#define IDC_VIEWHIGHSCORES              1106
#define IDC_CLEAR                       1107
#define IDC_BUTTON3                     1108
#define IDC_RESETGAME                   1109
#define IDC_ABOUT                       1110
#define IDC_DISPLAY_STATIC              1111
#define IDC_SETTINGS                    1112
#define IDC_DICEROLLSOUND               1114
#define IDC_YAHTZEESOUND                1115
#define IDC_EXITSOUND                   1116
#define IDC_SCORESOUND                  1117
#define IDC_BONUSSOUND                  1118
#define IDC_HIGHSCORESOUND              1119
#define IDC_BUTTON2                     1120

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
